[versions]
activityCompose = "1.10.1"
appcompatResources = "1.7.1"
checkerQual = "3.49.5"
composeBomVersion = "2025.06.00"
constraintlayout = "2.2.1"
coreKtx = "1.16.0"
cronetEmbedded = "119.6045.31"
documentfile = "1.1.0"
espressoCore = "3.6.1"
fragmentKtx = "1.8.8"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlin = "2.1.10"
androidGradlePlugin = "8.12.0"
kotlinStdlib = "2.1.21"
kotlinxCoroutinesAndroid = "1.10.2"
leanback = "1.2.0"
lifecycleLivedataKtx = "2.9.1"
material = "1.12.0"
navigationFragmentKtx = "2.9.0"
orgEclipseJdtAnnotation = "2.3.100"
preferenceKtx = "1.2.1"
runtime = "1.8.2"
uiToolingPreview = "1.8.2"
appcompat = "1.7.1"
activity = "1.8.0"
[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityCompose" }
androidx-appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompatResources" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.6.1" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-junit = { module = "androidx.test.ext:junit", version = "1.3.0" }
androidx-leanback = { module = "androidx.leanback:leanback", version.ref = "leanback" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version = "2.9.2" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version = "2.9.2" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version = "2.9.3" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version = "2.9.3" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version = "1.8.3" }
androidx-ui = { module = "androidx.compose.ui:ui", version = "1.8.3" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version = "1.8.3" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version = "1.8.3" }
checker-qual = { module = "org.checkerframework:checker-qual", version.ref = "checkerQual" }
compose-bom = { module = "androidx.compose:compose-bom", version = "2025.07.00" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version = "2.2.0" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version = "2.2.0" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version = "2.2.0" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinxCoroutinesAndroid" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
org-eclipse-jdt-annotation = { module = "org.eclipse.jdt:org.eclipse.jdt.annotation", version.ref = "orgEclipseJdtAnnotation" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

[plugins]
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
